/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <math.h>
/* Header for class core_wave_WaveView */

#ifndef _Included_core_wave_WaveView
#define _Included_core_wave_WaveView
#ifdef __cplusplus
extern "C" {
#endif
#undef core_wave_WaveView_SAMPLING_SIZE
#define core_wave_WaveView_SAMPLING_SIZE 64L
/*
 * Class:     core_wave_WaveView
 * Method:    nativeCalcValue
 * Signature: (FF)D
 */
JNIEXPORT jdouble JNICALL Java_core_wave_WaveView_nativeCalcValue
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
